default: 
    autoload:
        '': '%paths.base%/../features/bootstrap'
    suites:
        default:
            paths: ['../features/local']
            contexts:
                - FeatureContext:
                    parameters:
                        server: "hub-cloud.browserstack.com"
                        user: "BROWSERSTACK_USERNAME"
                        key: "BROWSERSTACK_ACCESS_KEY"

                        capabilities:
                            build: "browserstack build 1"
                            name: "BStack local test"
                            "browserstack.debug": true
                            "browserstack.local": true
                            "browserstack.source": "behat:sample-master-v1.0"

                        environments:
                            -
                                browser: "Chrome"
                                os: "Windows"
