default:
    paths:
        features: '../features/single'
        bootstrap:  '../features/bootstrap'
    context:
        parameters:
            browserstack:
                server: "hub-cloud.browserstack.com"
                user: "BROWSERSTACK_USERNAME"
                key: "BROWSERSTACK_ACCESS_KEY"

                capabilities:
                    build: "behat-browserstack"
                    name: "parallel_test"
                    "browserstack.debug": true

                environments:
                    -
                        browser: "chrome"
                    -
                        browser: "firefox"
                    -
                        browser: "safari"
                    -
                        browser: "internet explorer"
